# -*- coding: utf-8 -*-
"""HW#1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R1BcoGaWCoagNFwdQIS6VkrtG2FKeaz9
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')
data = '/content/drive/MyDrive/qm9.csv'

df = pd.read_csv(data, sep=",")
df.head()

df.sample(n=20000, random_state=26)

# Сохранить таблицу в формат csv
df_sample = df.sample(n=20000, random_state=26)
df_sample.to_csv('/content/drive/MyDrive/qm9_sample.csv', index=False)